name: disaster-pipeline
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - click=8.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - flask=2.0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - greenlet=1.1.1
  - icc_rt=2019.0.0
  - icu=64.2
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - itsdangerous=2.0.1
  - jedi=0.18.2
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.4.8
  - jupyter_core=5.1.0
  - kiwisolver=1.4.4
  - langdetect=1.0.9
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.0.9
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvmlite=0.39.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - nltk=3.7
  - numba=0.56.4
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.2
  - parso=0.8.3
  - phik=0.11.2
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - platformdirs=2.6.0
  - plotly=5.11.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.13.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pywin32=305
  - pyzmq=23.2.0
  - qt=5.9.7
  - regex=2022.3.15
  - scikit-learn=1.1.3
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=65.5.0
  - sip=4.19.13
  - six=1.16.0
  - sqlalchemy=1.4.32
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tbb=2021.6.0
  - tenacity=8.0.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.7.0
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.8
  - zeromq=4.3.4
  - zlib=1.2.13